spring:
  application:
    name : lastsecond-flight
  datasource:
    url: jdbc:postgresql://localhost:5433/lastsecond_flight
    username: postgres
    password: Dbpass2
  liquibase:
      enabled: true
      change-log: "classpath:liquibase-changeLog.xml"
  jpa:
      hibernate:
        ddl-auto: validate
server:
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:keystore/baeldung.p12"
    key-store-password: javazxc
    key-alias: baeldung
    enabled: true
trust:
  store: "classpath:keystore/baeldung.p12"
  password: javazxc


