spring:
  application:
    name=lastsecond-trip
server:
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:keystore/baeldung.p12"
    key-store-password: javazxc
    key-alias: baeldung
    enabled: true
  port: 8443
trust:
  store: "classpath:keystore/baeldung.p12"
  password: javazxc