spring:
  application:
    name : lastsecond-hotel
  datasource:
    url: jdbc:postgresql://localhost:5433/lastsecond_hotel
    username: postgres
    password: Dbpass2
  liquibase:
      enabled: true
      change-log: "classpath:liquibase-changeLog2.xml"
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
server:
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:keystore/baeldung.p12"
    key-store-password: javazxc
    key-alias: baeldung
    enabled: true
  port: 8081
trust:
  store: "classpath:keystore/baeldung.p12"
  password: javazxc


